# Generated by jeweler
# DO NOT EDIT THIS FILE DIRECTLY
# Instead, edit Jeweler::Tasks in Rakefile, and run 'rake gemspec'
# -*- encoding: utf-8 -*-

Gem::Specification.new do |s|
  s.name = %q{simplegeo}
  s.version = "0.2.1"

  s.required_rubygems_version = Gem::Requirement.new(">= 0") if s.respond_to? :required_rubygems_version=
  s.authors = ["Dan Dofter", "Bryan Ryckbost", "Andrew Mager", "Peter Bell"]
  s.date = %q{2011-03-30}
  s.email = %q{andrew@simplegeo.com}
  s.extra_rdoc_files = [
    "LICENSE",
    "README.rdoc"
  ]
  s.files = [
    ".document",
    "Gemfile",
    "LICENSE",
    "README.rdoc",
    "Rakefile",
    "VERSION",
    "lib/simple_geo.rb",
    "lib/simple_geo/client.rb",
    "lib/simple_geo/connection.rb",
    "lib/simple_geo/endpoint.rb",
    "lib/simple_geo/hash_utils.rb",
    "lib/simple_geo/record.rb",
    "lib/simplegeo.rb",
    "simplegeo.gemspec",
    "spec/cassettes/feature_valid.yml",
    "spec/cassettes/get_categories.yml",
    "spec/client_spec.rb",
    "spec/feature_spec.rb",
    "spec/fixtures/contains.json",
    "spec/fixtures/context.json",
    "spec/fixtures/empty_feature_collection.json",
    "spec/fixtures/get_density_by_day.json",
    "spec/fixtures/get_density_by_hour.json",
    "spec/fixtures/get_history.json",
    "spec/fixtures/get_nearby.json",
    "spec/fixtures/get_record.json",
    "spec/fixtures/get_records.json",
    "spec/fixtures/layer_info.json",
    "spec/fixtures/nearby_address.json",
    "spec/fixtures/no_such_record.json",
    "spec/fixtures/nonetype_not_iterable.json",
    "spec/fixtures/overlaps.json",
    "spec/fixtures/places.json",
    "spec/fixtures/places_category.json",
    "spec/fixtures/places_category_and_q.json",
    "spec/fixtures/places_q.json",
    "spec/spec.opts",
    "spec/spec_helper.rb",
    "vcr/cassettes/feature_valid.yml",
    "vcr/cassettes/feature_valid.yml.invalid"
  ]
  s.homepage = %q{https://github.com/simplegeo/simplegeo-ruby}
  s.require_paths = ["lib"]
  s.rubygems_version = %q{1.6.2}
  s.summary = %q{A SimpleGeo Ruby Client}
  s.test_files = [
    "spec/client_spec.rb",
    "spec/feature_spec.rb",
    "spec/spec_helper.rb"
  ]

  if s.respond_to? :specification_version then
    s.specification_version = 3

    if Gem::Version.new(Gem::VERSION) >= Gem::Version.new('1.2.0') then
      s.add_runtime_dependency(%q<fakeweb>, [">= 0"])
      s.add_runtime_dependency(%q<oauth>, [">= 0"])
      s.add_runtime_dependency(%q<json_pure>, [">= 0"])
      s.add_runtime_dependency(%q<rcov>, [">= 0"])
      s.add_runtime_dependency(%q<rspec>, [">= 0"])
      s.add_runtime_dependency(%q<vcr>, [">= 0"])
      s.add_runtime_dependency(%q<oauth>, [">= 0.4.0"])
      s.add_runtime_dependency(%q<json_pure>, [">= 0"])
      s.add_development_dependency(%q<rspec>, [">= 1.2.0"])
      s.add_development_dependency(%q<fakeweb>, [">= 1.2.0"])
      s.add_development_dependency(%q<vcr>, [">= 1.6.0"])
    else
      s.add_dependency(%q<fakeweb>, [">= 0"])
      s.add_dependency(%q<oauth>, [">= 0"])
      s.add_dependency(%q<json_pure>, [">= 0"])
      s.add_dependency(%q<rcov>, [">= 0"])
      s.add_dependency(%q<rspec>, [">= 0"])
      s.add_dependency(%q<vcr>, [">= 0"])
      s.add_dependency(%q<oauth>, [">= 0.4.0"])
      s.add_dependency(%q<json_pure>, [">= 0"])
      s.add_dependency(%q<rspec>, [">= 1.2.0"])
      s.add_dependency(%q<fakeweb>, [">= 1.2.0"])
      s.add_dependency(%q<vcr>, [">= 1.6.0"])
    end
  else
    s.add_dependency(%q<fakeweb>, [">= 0"])
    s.add_dependency(%q<oauth>, [">= 0"])
    s.add_dependency(%q<json_pure>, [">= 0"])
    s.add_dependency(%q<rcov>, [">= 0"])
    s.add_dependency(%q<rspec>, [">= 0"])
    s.add_dependency(%q<vcr>, [">= 0"])
    s.add_dependency(%q<oauth>, [">= 0.4.0"])
    s.add_dependency(%q<json_pure>, [">= 0"])
    s.add_dependency(%q<rspec>, [">= 1.2.0"])
    s.add_dependency(%q<fakeweb>, [">= 1.2.0"])
    s.add_dependency(%q<vcr>, [">= 1.6.0"])
  end
end

